export const FETCH_ADS_REQUEST = 'FETCH_ADS_REQUEST';
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';

export const SAVED_AD_REQUEST = 'SAVED_AD_REQUEST';
export const SAVED_AD_FAILURE = 'SAVED_AD_FAILURE';
export const SAVED_AD_SUCCESS = 'SAVED_AD_SUCCESS';

// export const SET_FILTER = 'SET_FILTER';