export const FETCH_ADS_REQUEST = 'FETCH_ADS_REQUEST';
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';

export const AD_SAVE_REQUEST = 'AD_SAVE_REQUEST';
export const AD_SAVE_FAILURE = 'AD_SAVE_FAILURE';
export const AD_SAVE_SUCCESS = 'AD_SAVE_SUCCESS';

// export const SET_FILTER = 'SET_FILTER';